;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        end-of-visual-line
        forward-sexp
        org-delete-char
        org-force-self-insert
        org-metaright
        org-shiftmetaright
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        end-of-buffer
        fiplr-find-file
        ido-switch-buffer
        js2-mode-show-node
        org-return
        org-self-insert-command
        save-some-buffers
        suspend-frame
        yas-expand
        ))
